### PR TITLE
return a subscription id from `subscribe`

### PR DESCRIPTION
**Pull request by vesparny**
As reported in https://github.com/styled-components/styled-components/pull/1049/ this implementation should improve performance in case of big amount of subscriptions.

Instead of allocating and returning an `unsubscribe` function, `subscribe` only returns a subscription id that will be used with the new method `.unsubscribe(subId)`

I'd like to benchmark this version against previous one.

In case we merge it, it will be a breaking change.
`glamorous` and `theming` would also benefit from it.

I also saw on open PR on `mitt` for introducing the current `brcast` implementation.
https://github.com/developit/mitt/pull/42

Perhaps @developit knows better performance implications?

cc @mxstbr @kentcdodds @iamstarkov

#### TODO

- [ ] document API

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Sounds fine to me. Should there be a README update too?

**Comment by vesparny** [comment]
@kentcdodds yep

**Comment by vesparny** [comment]
Hi @philpl, your comments should be addressed.
Thanks

**Comment by iamstarkov** [comment]
> I'd like to benchmark this version against previous one.

@vesparny, did you bench it?

**Comment by vesparny** [comment]
@iamstarkov nope.
The performance issue has been raised in the SC repo that uses a similar implementation.

Here is the reference commit 
https://github.com/styled-components/styled-components/pull/1049/commits/c451f74784e9e9606e91a0950f21cc42f8c4a1e5

I'd like to benchmark it too but didn't have time.

**Pull request merged**
